MyFirstDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", main, name="main"),
    path("lovely/", include("lovely.urls")),
    path("posts/", include("posts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lovely/urls.py
from django.urls import path
from lovely.views import first, second, third


app_name = "lovely"
urlpatterns = [
    path("first/", first, name="first"),
    path("second/", second, name="second"),
    path("third/", third, name="third"),
]

my_site_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path
from .views import new, create, show, edit, update, delete


app_name = "posts"
urlpatterns = [
    path("new/", new, name="new"),
    path("create/", create, name="create"),
    path("<int:post_id>/", show, name="show"),  # 꺽새 안에 주소를 통해 데이터 받을 수 있음 <자료형:변수명>
    path("edit/<int:post_id>", edit, name="edit"),
    path("update/<int:post_id>", update, name="update"),
    path("delete/<int:post_id>", delete, name="delete"),
]

lovely/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    class Meta:
        ordering = ["-created_at"]  # 정렬 방법 1
        pass

    POST_TYPES = [
        (0, "칼럼"),
        (1, "뉴스"),
        (2, "소설"),
    ]

    title = models.CharField(max_length=50, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    view_count = models.IntegerField(default=0, verbose_name="조회수")

    _type = models.PositiveSmallIntegerField(choices=POST_TYPES, verbose_name="게시글 종류")

    image = models.ImageField(
        upload_to="posts/img",
        default="posts/default/default_img.jpg",
        verbose_name="이미지",
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="등록 시간")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="수정 시간")

    def __str__(self):
        return self.title

    # 자동으로 해당 url을 반환해주는 함수. 수동 호출이 아닌 자동 호출. 추후 클래스 베이스드 뷰에서 디테일 뷰에 자동 연결
    def get_absolute_url(self,):
        return reverse("posts:show", args=[self.id])

posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    _type = forms.ChoiceField(
        widget=forms.RadioSelect, label="게시글 종류", choices=Post.POST_TYPES, required=True
    )

    class Meta:
        model = Post
        fields = ["title", "_type", "content", "image"]
        labels = {"title": "제목", "content": "내용", "image": "사진"}
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
        }

lovely/views.py
from django.shortcuts import render


def first(request):
    return render(request, 'lovely/first.html')


def second(request):
    return render(request, 'lovely/second.html')


def third(request):
    return render(request, 'lovely/third.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Post
from .forms import PostForm

import pdb


def main(request):
    context = {
        "posts": Post.objects.all(),  # 정렬 방법 1. models.py에서 해주는 방법
        # "posts": Post.objects.order_by("-created_at"), # 정렬 방법 2
    }

    return render(request, "posts/main.html", context)


def new(request):
    context = {
        "form": PostForm(),  # PostForm 양식 전달
    }

    return render(request, "posts/new.html", context)


@require_POST  # 데코레이터(메서드를 꾸며주는 역할)로 애초에 POST 방식의 값만 받도록 설정
def create(request):
    form = PostForm(
        request.POST, request.FILES or None  # PostForm에 넣어줄 때도 FILES 안에 들어있는 이미지도 함께
    )  # POSTFORM이라는 모델에 전달받은 객체 넣고 생성
    if form.is_valid():
        form.save()

    # return redirect("main") # 첫번째 방법
    return redirect(form.instance)


def show(request, post_id):  # 방법 2. 주소에서 값 전달 -> urls.py에서 post_id 전달해준거 받기
    # 방법 1
    # post_id = request.GET.get("post_id")  # 받은 url에서 post_id라는 인자 값 얻고
    # post = Post.objects.get(id=post_id)  # Post 객체들 중에 해당 post_id를 id(Primary key)로 갖고 있는 친구를 찾아서
    post = get_object_or_404(Post, id=post_id)
    context = {
        "post": post,
    }  # context에 딕셔너리 형태로 넣어주고

    post.view_count += 1
    post.save()  # 객체 저장

    return render(request, "posts/show.html", context)  # 템플릿에 전달하면 해당 html(템플릿) 안에서 출력


def edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = {
        "form": PostForm(instance=post),  # 해당 id를 가지고 원래 있던 데이터를 인스턴스에 저장
        "post": post,  # update 할 때 참조용
    }

    return render(request, "posts/edit.html", context)


@require_POST
def update(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST,
        request.FILES or None,  # PostForm에 넣어줄 때도 FILES 안에 들어있는 이미지도 함께
        instance=post,
    )  # instance 속성을 붙여 줌으로써 새로 생성이 아닌 있는 인스턴스를 수정
    if form.is_valid():
        form.save()

    # return redirect("posts:show", post_id)  # 게시글 화면으로 리다이렉트 / 원래 방법
    return redirect(
        post
    )  # 게시글 화면으로 리다이렉트 / 장고스런 방법. 왜? <- get_absolute_url이란 함수가 자동으로 객체의 url을 반환해줌.


@require_POST
def delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()  # 삭제하는 ORM
    return redirect("main")

MyFirstDjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/project.css' %}" />
    <title>My First dJango</title>
  </head>
  <body>
    {% include "share/_navbar.html" %} {% block content %} {% endblock %}
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

MyFirstDjango/templates/share/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href={% url "main" %}>Navbar</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">
          Home <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url "posts:new" %}>새 글 쓰기</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"
          >Disabled</a
        >
      </li>
    </ul>
  </div>
</nav>

lovely/templates/lovely/first.html
{% extends 'base.html' %} {% block content %}
<h1>first</h1>
{% endblock %}

lovely/templates/lovely/second.html
{% extends 'base.html' %}

{% block content %}
    <h2>second</h2>

{% endblock %}

lovely/templates/lovely/third.html
{% extends 'base.html' %} {% block content %}
<h1>third</h1>
{% endblock %}

posts/templates/posts/_form.html
{% csrf_token %}
{{ form.as_p }} <!-- 전달받은 PostForm 양식을 출력 -->
<input type="submit" value="{{ btn_value }}" class="btn btn-outline-primary">

posts/templates/posts/edit.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <h1>
        글 수정하기
    </h1>
    <form action="{% url "posts:update" post.id %}" method="POST" enctype="multipart/form-data"> <!-- enctype 중요! 없으면 파일 데이터 제대로 안 감. 이게 없으면 request.POST만 간다.--> <!-- 수정 용 -->
        {%  include 'posts/_form.html' with form=form btn_value="글 수정하기"%}
        <!-- 중복 부분 _form.html으로 치환, with 뒤에 인자 넘겨주기 -->
    </form>
</div>
{% endblock %}

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>현스기의 블로그</h1>
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4 col-12">
            <div class="card" style="width: 18rem; margin-top: 20px;">
                {% if post.image %}
                    <img src="{{ post.image.url }}" class="card-img-top" alt="...">
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content }}</p>
                    <p>
                        {{ post.created_at }}
                    </p>
                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %} {% block content%}
<div class="container">
    <h1>
        새로운 글 작성하기
    </h1>
    <form action="{% url "posts:create"%}" method="POST" enctype="multipart/form-data"> <!-- enctype 중요! 없으면 파일 데이터 제대로 안 감. 이게 없으면 request.POST만 간다.-->
      {%  include 'posts/_form.html' with form=form btn_value="글 작성하기"%}
    </form>
</div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>게시글 상세 페이지 입니다.</h1>
    <h2>제목 : {{ post.title }}</h2>
    <h4>조회수 : {{ post.view_count }}</h4>
    <p>내용 : {{ post.content }}</p>
    <a href="{% url "posts:edit" post.id %}" class="btn btn-outline-primary">수정하기</a>
    <a href="#" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModal">삭제하기</a>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">정말 삭제하시겠습니까?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
        <form action="{% url "posts:delete" post.id %}" method="POST">
            {% csrf_token %} <!-- form 전달할 때 필수. 장고에서 제공하는 인증 키 -->
            <input type="submit" class="btn btn-danger" value="삭제"/>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}